# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db87cec2ff600f20f036ec76b877f3bf2ac659843c44d540f3a411fbb2399f2e89c3564c3e66412a95f422f3fa6aadd8f597eea5850ae58e69db5bf3efe9046

test:
  secret_key_base: eb582cfd34b05ca35b951db469564a01067dc087c60c66ee4a4b6cf053b7c7153cf07719e9fb48befed134f45aaff269ead290692860c04dd606bfeca8bd5dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
